import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import jobsRouter from "./jobs";
import invoicesRouter from "./invoices";
import expensesRouter from "./expenses";
import placementsRouter from "./placements";
import propertiesRouter from "./properties";
import tasksRouter from "./tasks";
import messagesRouter from "./messages";
import pushRouter from "./push";
import appointmentsRouter from "./appointments";
import dashboardRouter from "./dashboard";
import driveRouter from "./drive";
import pdfRouter from "./pdf";
import syncRouter from "./sync";
import docsRouter from "./docs";
import directoryRouter from "./directory";
import rentStatusRouter from "./rent-status";
import availablePropertiesRouter from "./available-properties";
import doorloopRouter from "./doorloop";
import formsRouter from "./forms";
import tenantNotesRouter from "./tenant-notes";

const router: IRouter = Router();

router.use(formsRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(jobsRouter);
router.use(pdfRouter);
router.use(invoicesRouter);
router.use(expensesRouter);
router.use(placementsRouter);
router.use(propertiesRouter);
router.use(tasksRouter);
router.use(messagesRouter);
router.use(pushRouter);
router.use(appointmentsRouter);
router.use(dashboardRouter);
router.use(driveRouter);
router.use(syncRouter);
router.use(docsRouter);
router.use(directoryRouter);
router.use(rentStatusRouter);
router.use(availablePropertiesRouter);
router.use(doorloopRouter);
router.use(tenantNotesRouter);
router.use(formsRouter);

export default router;
